language: java
sudo: enabled
services:
    - mysql
env:
    global:
     - TRAVIS=true
before_install:
    - sudo mysql -e 'CREATE DATABASE pruebas_db;'
    - sudo mysql -e 'SHOW DATABASES;'
    - sudo mysql -e 'USE prueba_db;'
    - sudo mysql -e 'select database();'
    - sudo mysql --version