version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
      - image: circleci/mysql:8.0.4
        command: [--default-autentication-plugin=mysql_native_password]
        environment: 
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
    # Add steps to the job
    steps:
      # Checkout the code as the first step.
      - checkout
      # Use mvn clean and package as the standard maven build phase
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      # Install MySQL Client
      - run:
          name: Install MySQL Client
          command: |
            sudo rm -rf /var/lin/apt/lists/*
            sudo apt-get update
            sudo apt-get install default-mysql-client --fix-missing
      # Then run your tests!
      - run:
          name: Test
          command: mvn test

# Invoke jobs via workflows
workflows:
  integration: 
    jobs:
      - build